theme: jekyll-theme-minimal
title: JC's Homepage
description: A fun homepage project for CS-HU250! CS-HU250 has been a fun and challenging class that I've been able 
to learn a lot from. Knowledge of Git and GitHub will definitely help me down the road.
